name: Deployment #workflow or pipeline name
on: push #event
jobs:
    lint-check:
        runs-on: ubuntu-latest #runner
        steps:
            - name: Get the code # install the code inside runner machine
              uses: actions/checkout@v6
            - name: Setup Node #install node js 
              uses: actions/setup-node@v6
              with:
                node-version: 24
            - name: install dependency # install dependencies
              run: npm ci
            - name: Check lint #check lint 
              run: npm run lint
    test:
        needs: lint-check #after lint-check, run the test
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v6
            - name: Setup Node 
              uses: actions/setup-node@v6
              with:
                node-version: 24
            - name: install dependency 
              run: npm ci
            - name: Run test #run test cases
              run: npm test
    deployment:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v6
            - name: Setup Node 
              uses: actions/setup-node@v6
              with:
                node-version: 24
            - name: install dependency 
              run: npm ci
            - name: Build code #build project 
              run: npm run build 
            - name: deploy #deployment 
              run: echo "deploy....."
