name: Output metadata
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps: 
            - name: Output the event details
              run: echo "${{toJSON(github.event)}}"
            - name: Output repo
              run: echo "${{toJSON(github.repository)}}"