name: Output metadata
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps: 
            - name: Output the event details
              run: echo "${{toJSON(github.event)}}"
            - name: Output issue
              run: echo "${{toJSON(github.repository)}}"